# Alacritty config - adding features back gradually
# Save as ~/.config/alacritty/alacritty.toml

[font]
normal = { family = "VictorMono Nerd Font" }
bold = { family = "VictorMono Nerd Font", style = "Bold" }
italic = { family = "VictorMono Nerd Font", style = "Italic" }
size = 12.0

[window]
opacity = 0.85
blur = true
padding = { x = 12, y = 12 }
dimensions = { columns = 120, lines = 40 }
decorations = "buttonless"

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

# Basic keyboard shortcuts
[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "Plus"
mods = "Control|Shift"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Back"
mods = "Control|Shift"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"

[colors.primary]
foreground = "#e1e3e4"
background = "#0d1117"

[colors.cursor]
text = "#0d1117"
cursor = "#58a6ff"

[colors.selection]
text = "#0d1117"
background = "#58a6ff"

[colors.hints]
start = { foreground = "#0d1117", background = "#73daca" }
end = { foreground = "#0d1117", background = "#73daca" }

[colors.normal]
black = "#484f58"
red = "#ff7b72"
green = "#3fb950"
yellow = "#d29922"
blue = "#58a6ff"
magenta = "#bc8cff"
cyan = "#39c5cf"
white = "#b1bac4"

[colors.bright]
black = "#6e7681"
red = "#ffa198"
green = "#56d364"
yellow = "#e3b341"
blue = "#79c0ff"
magenta = "#d2a8ff"
cyan = "#56d4dd"
white = "#f0f6fc"

[bell]
animation = "EaseOutExpo"
duration = 0

[scrolling]
history = 10000
multiplier = 3

# [url]
# launcher = { program = "open" }  # Change to "xdg-open" on Linux
# modifiers = "None"
